#!/usr/bin/env python3
"""run_tas.py — shared-input TAS run on both MesenCE oracle and cycle backend.

Usage:
  python3 tools/tas/run_tas.py --tas tas/sdb_4976.tas.json --frames 400 --out tas/runs/r400
    [--rom "roms/Super Dodge Ball (USA).nes"] [--shot-stride 5] [--skip-mesen|--skip-cyc]

The cycle backend (build-cycle/nes_game, upstream runner/cyc) is the only
recompilation under test: per-cycle CPU/PPU/APU, no extras.c, no patches.
Mesen side: TAS-driven Lua oracle (input in inputPolled, RAM/PPU bins +
state log per endFrame). Cycle side: absolute-state input schedule +
--frame-log-at mesen binary snapshots (RAM/CIRAM/palette/OAM/picture).

Outputs in OUT:
  input.tas.json, input.lua (mesen), input.cyc (cycle schedule),
  mesen/ (mesen_*.ppm/bin/meta, mesen_state.jsonl, mesen_nmi_log.txt),
  cyc/ (frames.bin CYCFRAME log, miss.txt, shots shot_*.png, cyc.log),
  run.json (provenance: rom sha, framework rev, tas sha, counts, exit codes).
"""
import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys

PROJ = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

ROM_NAME = "Super Dodge Ball (USA).nes"
CYC_DIR = os.path.join(PROJ, "build-cycle")
CYC_EXE = os.path.join(CYC_DIR, "nes_game")


def ensure_cyc_build(quiet=False):
    """Reconfigure + rebuild the cycle backend if inputs are newer than it.

    The cyc project regenerates code at configure/build time from the ROM +
    game config, so freshness is a plain mtime compare (no separate regen
    step, unlike the legacy runner). Raises RuntimeError on failure.
    Returns True if a build ran.
    """
    def log(*a):
        if not quiet:
            print("[build-cycle]", *a, file=sys.stderr)

    rom = os.path.join(PROJ, "roms", ROM_NAME)
    cfg = os.path.join(PROJ, "src", "game.toml")
    for p in (rom, cfg):
        if not os.path.exists(p):
            raise RuntimeError(f"missing build input: {p}")
    exe_mtime = os.path.getmtime(CYC_EXE) if os.path.exists(CYC_EXE) else -1
    stale = [p for p in (rom, cfg) if os.path.getmtime(p) > exe_mtime]
    if exe_mtime >= 0 and not stale:
        log("binary fresh, skipping build")
        return False
    log("stale inputs:", [os.path.basename(p) for p in stale] or ["(no binary)"],
        "— reconfiguring + rebuilding")
    sdl_dir = "/usr/lib/x86_64-linux-gnu/cmake/SDL2"
    cfg_cmd = ["cmake", "-S", "external/nesrecomp/runner/cyc/project", "-B", "build-cycle",
               f"-DNESRECOMP_ROM={rom}", f"-DNESRECOMP_GAME_CONFIG={cfg}",
               "-DNESRECOMP_HEADLESS=ON"]
    if os.path.isdir(sdl_dir):
        cfg_cmd.append(f"-DSDL2_DIR={sdl_dir}")
    for step in (cfg_cmd, ["cmake", "--build", "build-cycle", "-j", str(os.cpu_count() or 4)]):
        log("+", " ".join(step[:4]), "...")
        r = subprocess.run(step, cwd=PROJ, capture_output=True, text=True)
        if r.returncode != 0:
            sys.stderr.write((r.stdout or "")[-4000:])
            sys.stderr.write((r.stderr or "")[-4000:])
            raise RuntimeError("cycle build step failed (see output above)")
    log("rebuild complete")
    return True


def sha1_file(p):
    h = hashlib.sha1()
    with open(p, "rb") as f:
        h.update(f.read())
    return h.hexdigest()


def emit_lua(frames, path):
    with open(path, "w") as f:
        f.write("return {" + ",".join(str(m) for m in frames) + "}\n")


NAMES = [(0x80, "A"), (0x40, "B"), (0x20, "SELECT"), (0x10, "START"),
         (0x08, "UP"), (0x04, "DOWN"), (0x02, "LEFT"), (0x01, "RIGHT")]


def emit_schedule(frames, path):
    """tas.json -> cycle absolute-state schedule (`<frame> A+B...`, `-` = release).

    The host applies steps with step.frame <= frame, so TAS frame f state is
    emitted at f. One step per change (plus frame 0 when nonzero).
    """
    steps = []
    prev = None
    for f, m in enumerate(frames):
        if m != prev:
            steps.append(f"{f} " + ("+".join(n for bit, n in NAMES if m & bit) if m else "-"))
            prev = m
    open(path, "w").write("# generated by run_tas.py\n" + "\n".join(steps) + "\n")
    return steps


def run_mesen(rom, lua_tool, tas_lua, out_m, frames, stride, timeout=180):
    mesen_bin = os.path.join(PROJ, "external", "mesence", "Mesen")
    mesence_dir = os.path.join(PROJ, "external", "mesence")
    home = os.path.join(out_m, "_home")
    os.makedirs(home, exist_ok=True)
    for fn in ("settings.json", "MesenCore.so", "libHarfBuzzSharp.so", "libSkiaSharp.so"):
        src = os.path.join(mesence_dir, fn)
        if os.path.exists(src):
            shutil.copy(src, os.path.join(home, fn))
    env = dict(os.environ, HOME=home, OUT_DIR=os.path.abspath(out_m),
               TAS_LUA=os.path.abspath(tas_lua),
               MAX_FRAMES=str(frames), SHOT_STRIDE=str(stride))
    # remove stale lock
    for cand in (os.path.join(home, "mesen.lock"),
                 os.path.join(mesence_dir, "mesen.lock")):
        if os.path.exists(cand):
            os.remove(cand)
    cmd = ["xvfb-run", "-a", mesen_bin, "--testRunner", rom, lua_tool,
           f"--timeout={timeout}"]
    print("+", " ".join(cmd), file=sys.stderr)
    r = subprocess.run(cmd, env=env, capture_output=True, text=True, timeout=timeout + 60)
    open(os.path.join(out_m, "mesen_stdout.log"), "w").write(r.stdout or "")
    open(os.path.join(out_m, "mesen_stderr.log"), "w").write(r.stderr or "")
    return r.returncode


def run_cyc(rom, sched, out_c, frames, stride, timeout=600):
    shots = os.path.join(out_c, "shots")
    os.makedirs(shots, exist_ok=True)
    shot_base = os.path.join(shots, "shot.png")
    cmd = [CYC_EXE, rom, "--frames", str(frames), "--input", sched,
           "--ram-init", "zeros",
           "--frame-log-at", "mesen", "--frame-log", os.path.join(out_c, "frames.bin"),
           "--shot-every", str(stride), "--screenshot", shot_base,
           "--miss-log", os.path.join(out_c, "miss.txt")]
    print("+", " ".join(cmd), file=sys.stderr)
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        rc = r.returncode
        out = (r.stdout or "") + (r.stderr or "")
    except subprocess.TimeoutExpired as e:
        rc, out = 124, (e.stdout or "") if isinstance(e.stdout, str) else ""
    open(os.path.join(out_c, "cyc.log"), "w").write(out)
    m = re.search(r"frames=(\d+).*native_cycles=(\d+)", out)
    info = {"frames": int(m.group(1)) if m else None}
    m2 = re.search(r"\((\d+\.\d+)%\)", out)
    info["native_pct"] = float(m2.group(1)) if m2 else None
    info["rc"] = rc
    return info


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tas", required=True)
    ap.add_argument("--frames", type=int, required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--rom", default=os.path.join(PROJ, "roms", "Super Dodge Ball (USA).nes"))
    ap.add_argument("--shot-stride", type=int, default=1)
    ap.add_argument("--skip-mesen", action="store_true")
    ap.add_argument("--skip-cyc", action="store_true")
    ap.add_argument("--no-build", action="store_true",
                    help="skip the freshness rebuild (use existing binary as-is)")
    a = ap.parse_args()

    rebuilt = False
    if not a.skip_cyc and not a.no_build:
        rebuilt = ensure_cyc_build()

    tas = json.load(open(a.tas))
    frames = tas["frames"][:a.frames]
    os.makedirs(a.out, exist_ok=True)
    out_m = os.path.join(a.out, "mesen")
    out_c = os.path.join(a.out, "cyc")
    os.makedirs(out_m, exist_ok=True)
    os.makedirs(out_c, exist_ok=True)

    json.dump({"source_tas": a.tas, "frames": frames}, open(os.path.join(a.out, "input.tas.json"), "w"))
    sched = os.path.join(a.out, "input.cyc")
    steps = emit_schedule(frames, sched)
    tas_lua = os.path.join(a.out, "input.lua")
    emit_lua(frames, tas_lua)
    print(f"TAS frames={len(frames)} cyc_steps={len(steps)}", file=sys.stderr)

    rc_mesen = run_mesen(os.path.abspath(a.rom),
                         os.path.join(PROJ, "tools", "tas", "mesen_tas.lua"),
                         tas_lua, out_m, len(frames), a.shot_stride) if not a.skip_mesen else None
    cyc_info = run_cyc(os.path.abspath(a.rom), os.path.abspath(sched),
                       out_c, len(frames), a.shot_stride) if not a.skip_cyc else None

    fw = subprocess.run(["git", "-C", os.path.join(PROJ, "external", "nesrecomp"),
                         "rev-parse", "--short", "HEAD"],
                        capture_output=True, text=True).stdout.strip()
    run = {"tas": a.tas, "tas_frames": len(frames),
           "tas_sha1": sha1_file(a.tas), "rom_sha1": sha1_file(a.rom),
           "nesrecomp_head": fw, "shot_stride": a.shot_stride,
           "backend": "cycle", "rebuilt": rebuilt, "no_build": a.no_build,
           "mesen_rc": rc_mesen, "cyc": cyc_info}
    json.dump(run, open(os.path.join(a.out, "run.json"), "w"), indent=2)
    print(json.dumps(run, indent=2))


if __name__ == "__main__":
    main()
