#!/usr/bin/env python3
"""run_tas.py — shared-input TAS run on both MesenCE oracle and recomp.

Usage:
  python3 tools/tas/run_tas.py --tas tas/sdb_4976.tas.json --frames 400 --out tas/runs/r400
    [--rom "roms/Super Dodge Ball (USA).nes"] [--shot-stride 5] [--skip-mesen|--skip-recomp]

Outputs in OUT:
  input.tas.json, input.script, input.lua,
  mesen/ (mesen_*.ppm/bin/meta, mesen_state.jsonl, mesen_nmi_log.txt),
  recomp/ (frame_*.png, smoke.json, wram.jsonl, ppu.jsonl, cosim.jsonl, apu.jsonl, stdout.log),
  run.json (provenance: rom sha, framework rev, tas sha, counts, exit codes).
"""
import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys

PROJ = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

ROM_NAME = "Super Dodge Ball (USA).nes"
GAME_PREFIX = "Super_Dodge_Ball_(USA)"


def ensure_fresh_build(quiet=False):
    """Rebuild the game binary if inputs are newer than it.

    Covers the known cmake gap: the regen custom command does not reliably
    retrigger after game.toml/extras.c edits, and TAS runs otherwise use
    whatever binary exists. Compares mtimes; on staleness runs the
    recompiler manually (confirming [Eval] Coverage) then cmake build.
    Raises RuntimeError on failure. Returns True if a rebuild ran.
    """
    def log(*a):
        if not quiet:
            print("[build]", *a, file=sys.stderr)

    src_dir = os.path.join(PROJ, "src")
    gen_dir = os.path.join(PROJ, "generated")
    build_dir = os.path.join(PROJ, "build")
    exe = os.path.join(build_dir, "super_dodgeball")
    rom = os.path.join(PROJ, "roms", ROM_NAME)
    inputs = [os.path.join(src_dir, f) for f in ("game.toml", "extras.c", "CMakeLists.txt")]
    missing = [p for p in inputs + [rom] if not os.path.exists(p)]
    if missing:
        raise RuntimeError(f"missing build inputs: {missing}")
    exe_mtime = os.path.getmtime(exe) if os.path.exists(exe) else -1
    stale = [p for p in inputs if os.path.getmtime(p) > exe_mtime]
    if exe_mtime >= 0 and not stale:
        log("binary fresh, skipping build")
        return False
    log("stale inputs:", [os.path.basename(p) for p in stale] or ["(no binary)"],
        "— regenerating + rebuilding")
    recomp = os.path.join(PROJ, "external", "nesrecomp", "recompiler", "build", "NESRecomp")
    if not os.path.exists(recomp):
        raise RuntimeError(f"recompiler binary missing: {recomp}")
    r = subprocess.run([recomp, rom, "--game", os.path.join(src_dir, "game.toml"),
                        "--output-prefix", GAME_PREFIX],
                       cwd=PROJ, capture_output=True, text=True)
    sys.stderr.write(r.stdout or "")
    sys.stderr.write(r.stderr or "")
    if r.returncode != 0 or "could not load game config" in (r.stdout or ""):
        raise RuntimeError("NESRecomp regen failed (see output above)")
    for step in (["cmake", "-S", "src", "-B", "build", "-G", "Ninja",
                  "-DCMAKE_BUILD_TYPE=Release"],
                 ["cmake", "--build", "build", "-j", str(os.cpu_count() or 4)]):
        log("+", " ".join(step))
        r = subprocess.run(step, cwd=PROJ, capture_output=True, text=True)
        if r.returncode != 0:
            sys.stderr.write((r.stdout or "")[-4000:])
            sys.stderr.write((r.stderr or "")[-4000:])
            raise RuntimeError(f"build step failed: {' '.join(step[:3])}")
    log("rebuild complete")
    return True


def sha1_file(p):
    h = hashlib.sha1()
    with open(p, "rb") as f:
        h.update(f.read())
    return h.hexdigest()


def emit_lua(frames, path):
    with open(path, "w") as f:
        f.write("return {" + ",".join(str(m) for m in frames) + "}\n")


NAMES = [(0x80, "A"), (0x40, "B"), (0x20, "SELECT"), (0x10, "START"),
         (0x08, "UP"), (0x04, "DOWN"), (0x02, "LEFT"), (0x01, "RIGHT")]


def emit_script(frames, path):
    cmds = ["WAIT 1"]
    pending, prev = 0, 0
    for m in frames[1:]:
        newly, gone = m & ~prev, prev & ~m
        prev = m
        if newly or gone:
            if pending:
                cmds.append(f"WAIT {pending}")
                pending = 0
            for bit, n in NAMES:
                if newly & bit:
                    cmds.append(f"HOLD {n}")
            for bit, n in NAMES:
                if gone & bit:
                    cmds.append(f"RELEASE {n}")
        else:
            pending += 1
    if pending:
        cmds.append(f"WAIT {pending}")
    # Tail: runner exits when the script completes, so outlive any --smoke count.
    cmds.append("WAIT 1000000")
    open(path, "w").write("# generated by run_tas.py\n" + "\n".join(cmds) + "\n")
    return cmds


def run_mesen(rom, lua_tool, tas_lua, out_m, frames, stride, timeout=180):
    mesen_bin = os.path.join(PROJ, "external", "mesence", "Mesen")
    mesence_dir = os.path.join(PROJ, "external", "mesence")
    home = os.path.join(out_m, "_home")
    os.makedirs(home, exist_ok=True)
    for fn in ("settings.json", "MesenCore.so", "libHarfBuzzSharp.so", "libSkiaSharp.so"):
        src = os.path.join(mesence_dir, fn)
        if os.path.exists(src):
            shutil.copy(src, os.path.join(home, fn))
    env = dict(os.environ, HOME=home, OUT_DIR=os.path.abspath(out_m),
               TAS_LUA=os.path.abspath(tas_lua),
               MAX_FRAMES=str(frames), SHOT_STRIDE=str(stride))
    # remove stale lock
    for cand in (os.path.join(home, "mesen.lock"),
                 os.path.join(mesence_dir, "mesen.lock")):
        if os.path.exists(cand):
            os.remove(cand)
    cmd = ["xvfb-run", "-a", mesen_bin, "--testRunner", rom, lua_tool,
           f"--timeout={timeout}"]
    print("+", " ".join(cmd), file=sys.stderr)
    r = subprocess.run(cmd, env=env, capture_output=True, text=True, timeout=timeout + 60)
    open(os.path.join(out_m, "mesen_stdout.log"), "w").write(r.stdout or "")
    open(os.path.join(out_m, "mesen_stderr.log"), "w").write(r.stderr or "")
    return r.returncode


def run_recomp(rom, script, out_r, frames, timeout=120):
    exe = os.path.join(PROJ, "build", "super_dodgeball")
    shots = os.path.join(out_r, "shots")
    os.makedirs(shots, exist_ok=True)
    env = dict(os.environ,
               NESRECOMP_WRAM_TRACE=os.path.join(out_r, "wram.jsonl"),
               NESRECOMP_PPUMEM_TRACE=os.path.join(out_r, "ppu.jsonl"),
               NESRECOMP_COSIM_HASH=os.path.join(out_r, "cosim.jsonl"),
               NESRECOMP_APU_TRACE=os.path.join(out_r, "apu.jsonl"))
    cmd = [exe, rom, "--script", script, "--smoke", str(frames),
           "--smoke-interval", "1", "--save-screenshot", shots,
           "--smoke-output", os.path.join(out_r, "smoke.json")]
    print("+", " ".join(cmd), file=sys.stderr)
    try:
        r = subprocess.run(cmd, env=env, capture_output=True, text=True, timeout=timeout)
        rc = r.returncode
        out = (r.stdout or "") + (r.stderr or "")
    except subprocess.TimeoutExpired as e:
        rc, out = 124, (e.stdout or b"").decode() if isinstance(e.stdout, bytes) else (e.stdout or "")
    open(os.path.join(out_r, "recomp.log"), "w").write(out)
    return rc


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tas", required=True)
    ap.add_argument("--frames", type=int, required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--rom", default=os.path.join(PROJ, "roms", "Super Dodge Ball (USA).nes"))
    ap.add_argument("--shot-stride", type=int, default=1)
    ap.add_argument("--skip-mesen", action="store_true")
    ap.add_argument("--skip-recomp", action="store_true")
    ap.add_argument("--no-build", action="store_true",
                    help="skip the freshness rebuild (use existing binary as-is)")
    a = ap.parse_args()

    rebuilt = False
    if not a.skip_recomp and not a.no_build:
        rebuilt = ensure_fresh_build()

    tas = json.load(open(a.tas))
    frames = tas["frames"][:a.frames]
    os.makedirs(a.out, exist_ok=True)
    out_m = os.path.join(a.out, "mesen")
    out_r = os.path.join(a.out, "recomp")
    os.makedirs(out_m, exist_ok=True)
    os.makedirs(out_r, exist_ok=True)

    json.dump({"source_tas": a.tas, "frames": frames}, open(os.path.join(a.out, "input.tas.json"), "w"))
    script = os.path.join(a.out, "input.script")
    cmds = emit_script(frames, script)
    tas_lua = os.path.join(a.out, "input.lua")
    emit_lua(frames, tas_lua)
    print(f"TAS frames={len(frames)} script_cmds={len(cmds)}", file=sys.stderr)
    if len(cmds) > 4096:
        print("WARNING: script exceeds MAX_CMDS 4096 — recomp run will truncate", file=sys.stderr)

    rc_mesen = run_mesen(os.path.abspath(a.rom),
                         os.path.join(PROJ, "tools", "tas", "mesen_tas.lua"),
                         tas_lua, out_m, len(frames), a.shot_stride) if not a.skip_mesen else None
    rc_recomp = run_recomp(os.path.abspath(a.rom), os.path.abspath(script),
                           out_r, len(frames)) if not a.skip_recomp else None

    fw = subprocess.run(["git", "-C", os.path.join(PROJ, "external", "nesrecomp"),
                         "rev-parse", "--short", "HEAD"],
                        capture_output=True, text=True).stdout.strip()
    run = {"tas": a.tas, "tas_frames": len(frames),
           "tas_sha1": sha1_file(a.tas), "rom_sha1": sha1_file(a.rom),
           "nesrecomp_head": fw, "shot_stride": a.shot_stride,
           "rebuilt": rebuilt, "no_build": a.no_build,
           "mesen_rc": rc_mesen, "recomp_rc": rc_recomp}
    json.dump(run, open(os.path.join(a.out, "run.json"), "w"), indent=2)
    print(json.dumps(run, indent=2))


if __name__ == "__main__":
    main()
